name: GitHub Actions Context Dump

on:
  workflow_dispatch:

jobs:
  context-dump:
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub Context
        run: |
          echo "Dumping GitHub Context:"
          echo "${{ toJson(github) }}"
